export const numbers = [
  {
    value: 0,
    eastern: "٠",
    western: "0",
    arabic: "صِفْر",
    transliteration: "sifr",
    french: "zéro",
    audio: "/audio/0.mp3",
  },
  {
    value: 1,
    eastern: "١",
    western: "1",
    arabic: "وَاحِد",
    transliteration: "wahid",
    french: "un",
    audio: "/audio/1.mp3",
  },
  {
    value: 2,
    eastern: "٢",
    western: "2",
    arabic: "اِثْنَان",
    transliteration: "ithnan",
    french: "deux",
    audio: "/audio/2.mp3",
  },
  {
    value: 3,
    eastern: "٣",
    western: "3",
    arabic: "ثَلَاثَة",
    transliteration: "thalatha",
    french: "trois",
    audio: "/audio/3.mp3",
  },
  {
    value: 4,
    eastern: "٤",
    western: "4",
    arabic: "أَرْبَعَة",
    transliteration: "arba'a",
    french: "quatre",
    audio: "/audio/4.mp3",
  },
  {
    value: 5,
    eastern: "٥",
    western: "5",
    arabic: "خَمْسَة",
    transliteration: "khamsa",
    french: "cinq",
    audio: "/audio/5.mp3",
  },
  {
    value: 6,
    eastern: "٦",
    western: "6",
    arabic: "سِتَّة",
    transliteration: "sitta",
    french: "six",
    audio: "/audio/6.mp3",
  },
  {
    value: 7,
    eastern: "٧",
    western: "7",
    arabic: "سَبْعَة",
    transliteration: "sab'a",
    french: "sept",
    audio: "/audio/7.mp3",
  },
  {
    value: 8,
    eastern: "٨",
    western: "8",
    arabic: "ثَمَانِيَة",
    transliteration: "thamaniya",
    french: "huit",
    audio: "/audio/8.mp3",
  },
  {
    value: 9,
    eastern: "٩",
    western: "9",
    arabic: "تِسْعَة",
    transliteration: "tis'a",
    french: "neuf",
    audio: "/audio/9.mp3",
  },
  {
    value: 10,
    eastern: "١٠",
    western: "10",
    arabic: "عَشَرَة",
    transliteration: "ashara",
    french: "dix",
    audio: "/audio/10.mp3",
  },
  {
    value: 11,
    eastern: "١١",
    western: "11",
    arabic: "أَحَدَ عَشَرَ",
    transliteration: "ahada ashar",
    french: "onze",
    audio: "/audio/11.mp3",
  },
  {
    value: 12,
    eastern: "١٢",
    western: "12",
    arabic: "اِثْنَا عَشَرَ",
    transliteration: "ithna ashar",
    french: "douze",
    audio: "/audio/12.mp3",
  },
  {
    value: 13,
    eastern: "١٣",
    western: "13",
    arabic: "ثَلَاثَةَ عَشَرَ",
    transliteration: "thalathata ashar",
    french: "treize",
    audio: "/audio/13.mp3",
  },
  {
    value: 14,
    eastern: "١٤",
    western: "14",
    arabic: "أَرْبَعَةَ عَشَرَ",
    transliteration: "arba'ata ashar",
    french: "quatorze",
    audio: "/audio/14.mp3",
  },
  {
    value: 15,
    eastern: "١٥",
    western: "15",
    arabic: "خَمْسَةَ عَشَرَ",
    transliteration: "khamsata ashar",
    french: "quinze",
    audio: "/audio/15.mp3",
  },
  {
    value: 16,
    eastern: "١٦",
    western: "16",
    arabic: "سِتَّةَ عَشَرَ",
    transliteration: "sittata ashar",
    french: "seize",
    audio: "/audio/16.mp3",
  },
  {
    value: 17,
    eastern: "١٧",
    western: "17",
    arabic: "سَبْعَةَ عَشَرَ",
    transliteration: "sab'ata ashar",
    french: "dix-sept",
    audio: "/audio/17.mp3",
  },
  {
    value: 18,
    eastern: "١٨",
    western: "18",
    arabic: "ثَمَانِيَةَ عَشَرَ",
    transliteration: "thamaniyata ashar",
    french: "dix-huit",
    audio: "/audio/18.mp3",
  },
  {
    value: 19,
    eastern: "١٩",
    western: "19",
    arabic: "تِسْعَةَ عَشَرَ",
    transliteration: "tis'ata ashar",
    french: "dix-neuf",
    audio: "/audio/19.mp3",
  },
  {
    value: 20,
    eastern: "٢٠",
    western: "20",
    arabic: "عِشْرُون",
    transliteration: "ishrun",
    french: "vingt",
    audio: "/audio/20.mp3",
  },
  {
    value: 30,
    eastern: "٣٠",
    western: "30",
    arabic: "ثَلَاثُون",
    transliteration: "thalathun",
    french: "trente",
    audio: "/audio/30.mp3",
  },
  {
    value: 40,
    eastern: "٤٠",
    western: "40",
    arabic: "أَرْبَعُون",
    transliteration: "arba'un",
    french: "quarante",
    audio: "/audio/40.mp3",
  },
  {
    value: 50,
    eastern: "٥٠",
    western: "50",
    arabic: "خَمْسُون",
    transliteration: "khamsun",
    french: "cinquante",
    audio: "/audio/50.mp3",
  },
  {
    value: 60,
    eastern: "٦٠",
    western: "60",
    arabic: "سِتُّون",
    transliteration: "sittun",
    french: "soixante",
    audio: "/audio/60.mp3",
  },
  {
    value: 70,
    eastern: "٧٠",
    western: "70",
    arabic: "سَبْعُون",
    transliteration: "sab'un",
    french: "soixante-dix",
    audio: "/audio/70.mp3",
  },
  {
    value: 80,
    eastern: "٨٠",
    western: "80",
    arabic: "ثَمَانُون",
    transliteration: "thamanun",
    french: "quatre-vingts",
    audio: "/audio/80.mp3",
  },
  {
    value: 90,
    eastern: "٩٠",
    western: "90",
    arabic: "تِسْعُون",
    transliteration: "tis'un",
    french: "quatre-vingt-dix",
    audio: "/audio/90.mp3",
  },
  {
    value: 100,
    eastern: "١٠٠",
    western: "100",
    arabic: "مِئَة",
    transliteration: "mi'a",
    french: "cent",
    audio: "/audio/100.mp3",
  },
]

// Ajouter la conjonction "wa" (et)
export const conjunctions = {
  wa: {
    arabic: "وَ",
    transliteration: "wa",
    french: "et",
    audio: "/audio/wa.mp3",
  },
}

// Fonction pour obtenir les dizaines (20, 30, 40, etc.)
export const getDizaines = () => {
  return numbers.filter((n) => n.value >= 20 && n.value <= 90 && n.value % 10 === 0)
}

// Fonction pour obtenir les unités (1-9)
export const getUnites = () => {
  return numbers.filter((n) => n.value >= 1 && n.value <= 9)
}
